// appointmentStatuses.js
const APPOINTMENT_STATUS_PENDING = 1;
const APPOINTMENT_STATUS_APPROVED = 2;
const APPOINTMENT_STATUS_COMPLETED = 3;
const APPOINTMENT_STATUS_CANCELLED = 4;

module.exports = {
  APPOINTMENT_STATUS_PENDING,
  APPOINTMENT_STATUS_APPROVED,
  APPOINTMENT_STATUS_COMPLETED,
  APPOINTMENT_STATUS_CANCELLED,
};
